name: darpan
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  auto_route: ^6.4.0
  stacked_generator: ^1.3.3
  stacked_hooks: ^0.2.2
  easy_widgets: ^0.0.7
  logger:
  smooth_page_indicator: ^1.1.0
  injectable: ^2.3.2
  get_storage: ^2.1.1
  firebase_core: ^2.22.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
