name: abhiyaan
description: A new Flutter project.
publish_to: "none"
version: 1.1.6+11
# Major.Minor.Patch+Build
#  Major - Major changes like UI/UX changes, new features, etc. Those changes that are not backward compatible.
#  Minor - Minor changes like bug fixes, performance improvements, etc. Those changes that are backward compatible.
#  Patch - Patch changes like small bug fixes, small improvements, etc. Those changes that are backward compatible.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Stacked Dependencies
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  auto_route: ^7.8.4
  stacked_generator: ^1.3.3
  stacked_hooks: ^0.2.2
  logger:

  # Firebase Dependencies
  firebase_core: ^2.22.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.13.0
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.8.0

  # Other Dependencies
  smooth_page_indicator: ^1.1.0
  injectable: ^2.3.2
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.3.5
  expandable: ^5.0.1
  flutter_screenutil: ^5.9.0
  share_plus: ^7.2.1
  flutter_local_notifications: ^17.2.2
  app_settings: ^5.1.1
  lottie: ^3.0.0
  flutter_animate: ^4.3.0
  http: ^1.1.2
  upgrader: ^9.0.0
  pinput: ^3.0.1
  mailer: ^6.0.1
  flutter_staggered_grid_view: ^0.7.0
  add_2_calendar: ^3.0.1
  in_app_review: ^2.0.9
  flutter_rating_bar: ^4.0.1
  story: ^1.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/gallery/
    - assets/images/auth/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/home/quick_links/
    - assets/images/community/
    - assets/images/home/societies/
    - assets/animations/

  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy/Gilroy-Regular.ttf
        - asset: fonts/Gilroy/Gilroy-SemiBold.ttf
        - asset: fonts/Gilroy/Gilroy-Bold.ttf
        - asset: fonts/Gilroy/Gilroy-Thin.ttf
        - asset: fonts/Gilroy/Gilroy-Medium.ttf
        - asset: fonts/Gilroy/Gilroy-Light.ttf
        - asset: fonts/Gilroy/Gilroy-ExtraBold.ttf
        - asset: fonts/Gilroy/Gilroy-Black.ttf
