name: abhiyaan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Stacked Dependencies
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  auto_route: ^7.8.4
  stacked_generator: ^1.3.3
  stacked_hooks: ^0.2.2
  logger:

  # Firebase Dependencies
  firebase_core: ^2.22.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.13.0
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.8.0

  # Other Dependencies
  smooth_page_indicator: ^1.1.0
  injectable: ^2.3.2
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  intl: 0.18.1
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.5
  shimmer: ^3.0.0
  expandable: ^5.0.1
  flutter_screenutil: ^5.9.0
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.2.0
  app_settings: ^5.1.1
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  http: ^1.1.2
  upgrader: ^8.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/community/
    - assets/images/home/societies/
    - assets/animations/

  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
