#!/bin/bash

# ANSI escape codes for colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to check Flutter project status
check_flutter_project() {
  local analyze_output
  analyze_output=$(flutter analyze 2>&1)

  if [[ $analyze_output == *"No issues found!"* ]]; then
    echo -e ""
    echo -e "${GREEN}Flutter analysis passed.${NC}"
  else
    echo -e ""
    echo -e "${RED}Error: Flutter analysis found issues.${NC}"
    echo -e "$analyze_output"
    exit 1
  fi
}

# Run dart format on the 'lib' directory for the staged files
git diff --cached --name-only --diff-filter=ACM | grep '\.dart$' | xargs dart format

# Add the formatted files to the staging area
git add .

# Check Flutter project status
check_flutter_project

# If everything is fine, allow the commit
echo -e "${GREEN}Formatting and Flutter checks passed.${NC}"
exit 0